### ISSUE TITLE
error with pow.

### ISSUE THREAD

**Issue by tylerw1369** [SteppoFF/iota.keccak.pow.node.js#1]
I used the dcurl to get my nano file set up and it says this to me.  
![capture](https://user-images.githubusercontent.com/39392335/52084128-9779b480-255e-11e9-9b81-42f76f48f036.PNG)

**Comment by tylerw1369** [comment]
i did copy it into the main folder with the name libccurl.so as well.

**Comment by SteppoFF** [comment]
Which version of nodeJS are you using?
The libccurl.so has to be in the folder, from which your final script gets executed.

**Comment by tylerw1369** [comment]
I am running v10. 15.  I have the libccurl file in the main folder with the main.js

**Comment by tylerw1369** [comment]
Does this have to be x64?

**Comment by tylerw1369** [comment]
Cancel that i got it working. I think...haha  I had to go into the modules. iota.keccak.js and change the file name to libccurl.so.  Im sure its because it had the .so on the end of it that it couldnt find the file.
